"""Type stubs for the compiled `_sentil` extension."""

from typing import Iterator, Optional

import numpy as np
from numpy.typing import NDArray

__version__: str

stats: object
synthesis: object
gpu: object

class SentilError(Exception): ...
class ParseError(SentilError): ...
class SemanticError(SentilError): ...
class EvaluationError(SentilError): ...

_Floats = NDArray[np.float64]
_ArrayLike = object

class TimeMode:
    Discrete: TimeMode
    Dense: TimeMode

class Interpolation:
    Linear: Interpolation
    ZeroOrderHold: Interpolation
    CubicSpline: Interpolation

class IntervalMethod:
    Wilson: IntervalMethod
    ClopperPearson: IntervalMethod
    Jeffreys: IntervalMethod
    AgrestiCoull: IntervalMethod

class NoiseInteraction:
    Additive: NoiseInteraction
    Multiplicative: NoiseInteraction

class SprtVerdict:
    AcceptH0: SprtVerdict
    AcceptH1: SprtVerdict
    Inconclusive: SprtVerdict

class BayesVerdict:
    Holds: BayesVerdict
    Fails: BayesVerdict
    Inconclusive: BayesVerdict

class SoftKind:
    LogSumExp: SoftKind
    ArithmeticGeometricMean: SoftKind

class Backend:
    Auto: Backend
    Gradient: Backend
    CmaEs: Backend
    Milp: Backend

class Config:
    def __init__(self, time: TimeMode = ...) -> None: ...
    @property
    def time(self) -> TimeMode: ...

class Robustness:
    resolved: bool
    satisfied: bool
    value: float
    lower: float
    upper: float
    def __float__(self) -> float: ...

class Interval:
    start: float
    end: float

class Expr:
    @staticmethod
    def var(name: str) -> Expr: ...
    @staticmethod
    def constant(value: float) -> Expr: ...
    def __add__(self, other: object) -> Expr: ...
    def __sub__(self, other: object) -> Expr: ...
    def __mul__(self, other: object) -> Expr: ...
    def __truediv__(self, other: object) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def __abs__(self) -> Expr: ...
    def __pow__(self, other: object, modulo: object = None) -> Expr: ...
    def __mod__(self, other: object) -> Expr: ...
    def sin(self) -> Expr: ...
    def cos(self) -> Expr: ...
    def tan(self) -> Expr: ...
    def sqrt(self) -> Expr: ...
    def exp(self) -> Expr: ...
    def log(self) -> Expr: ...
    def ln(self) -> Expr: ...
    def floor(self) -> Expr: ...
    def ceil(self) -> Expr: ...
    def min(self, other: object) -> Expr: ...
    def max(self, other: object) -> Expr: ...
    def __gt__(self, other: object) -> Formula: ...
    def __ge__(self, other: object) -> Formula: ...
    def __lt__(self, other: object) -> Formula: ...
    def __le__(self, other: object) -> Formula: ...

class Formula:
    @staticmethod
    def parse(text: str) -> Formula: ...
    @staticmethod
    def from_json(text: str) -> Formula: ...
    def to_json(self) -> str: ...
    @property
    def depth(self) -> int: ...
    @property
    def is_temporal(self) -> bool: ...
    @property
    def variables(self) -> list[str]: ...
    def __and__(self, other: Formula) -> Formula: ...
    def __or__(self, other: Formula) -> Formula: ...
    def __invert__(self) -> Formula: ...
    def __rshift__(self, other: Formula) -> Formula: ...
    def always(self, lower: float = 0.0, upper: Optional[float] = None) -> Formula: ...
    def eventually(self, lower: float = 0.0, upper: Optional[float] = None) -> Formula: ...
    def historically(self, lower: float = 0.0, upper: Optional[float] = None) -> Formula: ...
    def once(self, lower: float = 0.0, upper: Optional[float] = None) -> Formula: ...
    def next(self) -> Formula: ...
    def until(self, other: Formula, lower: float = 0.0, upper: Optional[float] = None) -> Formula: ...
    def since(self, other: Formula, lower: float = 0.0, upper: Optional[float] = None) -> Formula: ...
    def probability(self, threshold: float, op: str = ">=") -> Formula: ...
    def robustness(self, trace: Trace) -> float: ...
    def robustness_dense(self, trace: Trace) -> float: ...
    def robustness_signal(self, trace: Trace) -> _Floats: ...
    def robustness_dense_signal(self, trace: Trace) -> _Floats: ...
    def violations(self, trace: Trace) -> list[Interval]: ...
    def smooth_robustness(self, trace: Trace, config: Optional[SmoothConfig] = None) -> float: ...
    def smooth_value_and_gradient(
        self, trace: Trace, config: Optional[SmoothConfig] = None
    ) -> tuple[float, dict[str, list[float]]]: ...
    def smooth_gradient(
        self,
        model: SystemModel,
        initial: _ArrayLike,
        input: _ArrayLike,
        config: Optional[SmoothConfig] = None,
    ) -> tuple[float, list[float]]: ...
    def check(self, trace: Trace, lifting: LiftingRegistry, config: Optional[SmcConfig] = None) -> SmcResult: ...
    def check_conservative(self, trace: Trace, lifting: LiftingRegistry, config: Optional[SmcConfig] = None) -> SmcResult: ...
    def check_distribution(self, trace: Trace, lifting: LiftingRegistry, config: Optional[SmcConfig] = None) -> tuple[SmcResult, RobustnessDistribution]: ...
    def check_sequential(self, trace: Trace, lifting: LiftingRegistry, config: SprtConfig) -> SprtResult: ...
    def check_bayesian(self, trace: Trace, lifting: LiftingRegistry, config: BayesConfig) -> BayesResult: ...
    def check_rare_event(self, system: StochasticSystem, config: Optional[RareEventConfig] = None) -> RareEventResult: ...
    def check_rare_event_gpu(self, model: SimModel, config: Optional[RareEventConfig] = None) -> GpuSplittingEstimate: ...
    def find_counterexample(self, model: SystemModel, bounds: Bounds, max_iters: int = 200, smooth: Optional[SmoothConfig] = None) -> Witness: ...
    def falsify(self, model: SystemModel, bounds: Bounds, config: Optional[CmaConfig] = None, restarts: int = 1) -> Witness: ...

class Trace:
    def __init__(self, times: _ArrayLike, signals: Optional[dict[str, _ArrayLike]] = None) -> None: ...
    @staticmethod
    def indexed(len: int) -> Trace: ...
    @staticmethod
    def from_csv(text: str) -> Trace: ...
    @staticmethod
    def from_tsv(text: str) -> Trace: ...
    @staticmethod
    def from_path(path: str) -> Trace: ...
    def add_signal(self, name: str, values: _ArrayLike) -> None: ...
    def add_signals(self, signals: dict[str, _ArrayLike]) -> None: ...
    def __len__(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def times(self) -> _Floats: ...
    @property
    def variables(self) -> list[str]: ...
    def __getitem__(self, name: str) -> _Floats: ...
    def get(self, name: str, default: object = None) -> object: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def resample(self, times: _ArrayLike, interp: Interpolation) -> Trace: ...
    def prepare(self, interp: Interpolation) -> PreparedTrace: ...

class PreparedTrace:
    def resample(self, times: _ArrayLike) -> Trace: ...

class RingBuffer:
    def __init__(self, capacity: int) -> None: ...
    def push(self, time: float, value: float) -> Optional[tuple[float, float]]: ...
    def __len__(self) -> int: ...
    @property
    def capacity(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def is_full(self) -> bool: ...
    def clear(self) -> None: ...
    def __getitem__(self, index: int) -> tuple[float, float]: ...
    def get(self, index: int) -> Optional[tuple[float, float]]: ...
    def front(self) -> Optional[tuple[float, float]]: ...
    def back(self) -> Optional[tuple[float, float]]: ...
    def pop_front(self) -> Optional[tuple[float, float]]: ...
    def pop_back(self) -> Optional[tuple[float, float]]: ...
    def mean(self) -> Optional[float]: ...
    def variance(self) -> Optional[float]: ...
    def std_dev(self) -> Optional[float]: ...
    def min(self) -> Optional[float]: ...
    def max(self) -> Optional[float]: ...
    def recompute_statistics(self) -> None: ...
    def time_range(self) -> Optional[tuple[float, float]]: ...
    def at_time(self, time: float) -> Optional[float]: ...
    def closest_to_time(self, time: float) -> Optional[tuple[float, float]]: ...
    def between(self, start: float, end: float) -> list[tuple[float, float]]: ...

class Monitor:
    def __init__(self, formula: Formula | str, config: Optional[Config] = None) -> None: ...
    def robustness(self, trace: Trace) -> float: ...
    def robustness_signal(self, trace: Trace) -> _Floats: ...
    def violations(self, trace: Trace) -> list[Interval]: ...
    def update(self, time: float, values: dict[str, float]) -> Robustness: ...
    def update_packed(self, time: float, values: _ArrayLike) -> Robustness: ...
    def symbol_index(self, name: str) -> Optional[int]: ...
    def reset(self) -> None: ...
    def last_probability(self) -> Optional[float]: ...
    @property
    def formula(self) -> Formula: ...
    @property
    def config(self) -> Config: ...
    def check(self, trace: Trace, lifting: LiftingRegistry) -> SmcResult: ...
    def check_sequential(self, trace: Trace, lifting: LiftingRegistry, config: SprtConfig) -> SprtResult: ...
    def check_rare(self, system: StochasticSystem) -> RareEventResult: ...

class OnlineMonitor:
    def __init__(self, formula: Formula | str) -> None: ...
    @staticmethod
    def with_lifting(
        formula: Formula | str, lifting: LiftingRegistry, config: Optional[SmcConfig] = None
    ) -> OnlineMonitor: ...
    def update(self, time: float, values: dict[str, float]) -> Robustness: ...
    def update_packed(self, time: float, values: _ArrayLike) -> Robustness: ...
    def run(self, trace: Trace) -> list[Robustness]: ...
    def symbol_index(self, name: str) -> Optional[int]: ...
    @property
    def variable_count(self) -> int: ...
    def reset(self) -> None: ...
    def last_probability(self) -> Optional[float]: ...

class MultiMonitor:
    def __init__(self) -> None: ...
    def add(self, id: str, formula: Formula | str) -> None: ...
    def add_probabilistic(
        self, id: str, formula: Formula | str, lifting: LiftingRegistry,
        config: Optional[SmcConfig] = None,
    ) -> None: ...
    def remove(self, id: str) -> bool: ...
    def reset(self) -> None: ...
    def __len__(self) -> int: ...
    @property
    def ids(self) -> list[str]: ...
    def update(self, time: float, values: dict[str, float]) -> dict[str, Robustness]: ...
    def probability(self, id: str) -> Optional[float]: ...
    def probabilities(self) -> dict[str, Optional[float]]: ...

class FormulaBank:
    def __init__(self) -> None: ...
    def add(self, id: str, formula: Formula | str) -> None: ...
    @property
    def ids(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def robustness(self, trace: Trace) -> dict[str, float]: ...
    def robustness_dense(self, trace: Trace) -> dict[str, float]: ...

class ConfidenceInterval:
    lower: float
    upper: float
    level: float
    @property
    def width(self) -> float: ...

class NoiseModel:
    @staticmethod
    def dirac(value: float) -> NoiseModel: ...
    @staticmethod
    def gaussian(mean: float, std_dev: float) -> NoiseModel: ...
    @staticmethod
    def uniform(low: float, high: float) -> NoiseModel: ...
    @staticmethod
    def log_normal(mu: float, sigma: float) -> NoiseModel: ...
    @staticmethod
    def exponential(rate: float) -> NoiseModel: ...
    @staticmethod
    def gamma(shape: float, scale: float) -> NoiseModel: ...
    @staticmethod
    def beta(alpha: float, beta: float) -> NoiseModel: ...
    @staticmethod
    def weibull(shape: float, scale: float) -> NoiseModel: ...
    @staticmethod
    def rayleigh(scale: float) -> NoiseModel: ...
    @staticmethod
    def gumbel(location: float, scale: float) -> NoiseModel: ...
    @staticmethod
    def cauchy(location: float, scale: float) -> NoiseModel: ...
    @staticmethod
    def student_t(df: float, location: float, scale: float) -> NoiseModel: ...
    @staticmethod
    def truncated_normal(mean: float, std_dev: float, lower: float, upper: float) -> NoiseModel: ...
    @staticmethod
    def poisson(rate: float) -> NoiseModel: ...
    @staticmethod
    def binomial(trials: int, probability: float) -> NoiseModel: ...
    @staticmethod
    def bootstrap(residuals: list[float]) -> NoiseModel: ...
    @staticmethod
    def mixture(weights: list[float], components: list[NoiseModel]) -> NoiseModel: ...
    @staticmethod
    def fit_gaussian(samples: list[float]) -> NoiseModel: ...
    @staticmethod
    def fit_bootstrap(samples: list[float]) -> NoiseModel: ...
    @staticmethod
    def fit_bootstrap_reservoir(samples: list[float], max_samples: int) -> NoiseModel: ...
    @staticmethod
    def fit_gaussian_mixture(samples: list[float], components: int, max_iters: int) -> NoiseModel: ...
    @staticmethod
    def residuals(truth: list[float], sensor: list[float], interaction: NoiseInteraction) -> _Floats: ...
    def mean(self) -> Optional[float]: ...
    def variance(self) -> Optional[float]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(text: str) -> NoiseModel: ...
    @staticmethod
    def from_file(path: str) -> NoiseModel: ...

class LiftingRegistry:
    def __init__(self) -> None: ...
    def register(self, variable: str, model: NoiseModel, interaction: NoiseInteraction = ...) -> None: ...
    @property
    def variables(self) -> list[str]: ...
    @property
    def is_empty(self) -> bool: ...
    def lift(self, trace: Trace, seed: int = 42) -> Trace: ...

class SmcConfig:
    samples: int
    confidence: float
    seed: int
    method: IntervalMethod
    def __init__(self, samples: int = 10000, confidence: float = 0.95, seed: int = 42, method: IntervalMethod = ...) -> None: ...

class SmcResult:
    probability: float
    interval: ConfidenceInterval
    satisfactions: int
    samples: int
    holds: bool

class RobustnessDistribution:
    count: int
    mean: float
    variance: float
    min: float
    max: float
    @property
    def std_dev(self) -> float: ...

class SprtConfig:
    p0: float
    p1: float
    alpha: float
    beta: float
    max_samples: int
    seed: int
    def __init__(self, p0: float, p1: float, alpha: float = 0.05, beta: float = 0.05, max_samples: int = 100000, seed: int = 42) -> None: ...

class SprtResult:
    verdict: SprtVerdict
    samples: int
    log_likelihood: float

class BayesConfig:
    threshold: float
    bayes_factor: float
    max_samples: int
    seed: int
    def __init__(self, threshold: float, bayes_factor: float = 100.0, max_samples: int = 100000, seed: int = 42) -> None: ...

class BayesResult:
    verdict: BayesVerdict
    samples: int
    posterior: float

class SimExpr:
    @staticmethod
    def prev(index: int) -> SimExpr: ...
    @staticmethod
    def time() -> SimExpr: ...
    @staticmethod
    def constant(value: float) -> SimExpr: ...
    @staticmethod
    def noise(index: int) -> SimExpr: ...
    def __add__(self, other: object) -> SimExpr: ...
    def __sub__(self, other: object) -> SimExpr: ...
    def __mul__(self, other: object) -> SimExpr: ...
    def __truediv__(self, other: object) -> SimExpr: ...
    def __abs__(self) -> SimExpr: ...
    def sin(self) -> SimExpr: ...
    def cos(self) -> SimExpr: ...
    def tan(self) -> SimExpr: ...
    def sqrt(self) -> SimExpr: ...
    def exp(self) -> SimExpr: ...
    def log(self) -> SimExpr: ...
    def ln(self) -> SimExpr: ...
    def floor(self) -> SimExpr: ...
    def ceil(self) -> SimExpr: ...
    def min(self, other: object) -> SimExpr: ...
    def max(self, other: object) -> SimExpr: ...

class SimModel:
    def __init__(self, variables: list[str], dt: float, horizon: int, init: list[SimExpr], advance: list[SimExpr], noise: list[NoiseModel]) -> None: ...
    def simulate(self, seed: int = 42) -> Trace: ...
    def to_stochastic_system(self) -> StochasticSystem: ...
    @property
    def variables(self) -> list[str]: ...
    @property
    def dt(self) -> float: ...
    @property
    def horizon(self) -> int: ...

class StochasticSystem:
    def simulate(self, seed: int = 42) -> Trace: ...
    @property
    def variables(self) -> list[str]: ...
    @property
    def dt(self) -> float: ...
    @property
    def horizon(self) -> int: ...

class RareEventConfig:
    particles: int
    margin: float
    seed: int
    def __init__(self, particles: int = 4096, margin: float = 0.0, seed: int = 42) -> None: ...

class RareEventResult:
    probability: float
    violation_probability: float
    holds: bool
    simulations: int

class SmoothConfig:
    temperature: float
    kind: SoftKind
    def __init__(self, temperature: float = 10.0, kind: SoftKind = ...) -> None: ...

class Bounds:
    def __init__(self, lower: list[float], upper: list[float]) -> None: ...
    @staticmethod
    def unbounded(dimension: int) -> Bounds: ...
    @property
    def lower(self) -> list[float]: ...
    @property
    def upper(self) -> list[float]: ...
    @property
    def dimension(self) -> int: ...
    def clamp(self, point: list[float]) -> list[float]: ...

class SystemModel:
    @staticmethod
    def linear(a: list[list[float]], b: list[list[float]], x0: list[float], variables: list[str], dt: float, horizon: int) -> SystemModel: ...
    @property
    def input_dimension(self) -> int: ...

class SynthesisResult:
    input: _Floats
    robustness: float
    holds: bool
    backend: Backend

class SafetyFilter:
    def __init__(self, bounds: Bounds) -> None: ...
    def filter(self, nominal: list[float], barriers: list[tuple[list[float], float]] = ...) -> _Floats: ...

class ChanceReport:
    estimate: float
    lower_bound: float
    samples: int
    holds: bool

class ChanceConstraint:
    def __init__(self, spec: Formula, probability: float, confidence: float = 0.0, tightening: float = 0.0) -> None: ...
    def validate(self, system: StochasticSystem, samples: int = 1000, seed: int = 42) -> ChanceReport: ...

class Witness:
    input: _Floats
    robustness: float
    trace: Trace

class CmaConfig:
    population: int
    max_generations: int
    initial_step: float
    tol_step: float
    seed: int
    def __init__(self, population: int = 0, max_generations: int = 300, initial_step: float = 0.3, tol_step: float = 1e-11, seed: int = 42) -> None: ...

class Controller:
    def __init__(self, model: SystemModel, spec: Formula, input_width: int, budget_ns: int, bounds: Optional[Bounds] = None, smooth: Optional[SmoothConfig] = None) -> None: ...
    def control(self, state: list[float]) -> _Floats: ...

class SpecBuilder:
    def __init__(self, name: str) -> None: ...
    @staticmethod
    def available() -> list[str]: ...
    @staticmethod
    def from_file(path: str) -> SpecBuilder: ...
    def with_variant(self, variant: str) -> SpecBuilder: ...
    def with_param(self, name: str, value: float) -> SpecBuilder: ...
    @property
    def available_variants(self) -> list[str]: ...
    def parameters(self) -> dict[str, float]: ...
    def build_deterministic(self) -> str: ...
    def build_probabilistic(self) -> str: ...
    def build_formula(self) -> Formula: ...
    def build_probabilistic_formula(self) -> Formula: ...
    def build_lifting_registry(self) -> LiftingRegistry: ...
    def build_monitor(self) -> Monitor: ...
    def smc_settings(self) -> Optional[tuple[float, int]]: ...
    def sprt_settings(self) -> Optional[tuple[float, float, float, float, int]]: ...
    def ams_settings(self) -> Optional[tuple[int, int]]: ...

class GpuSplittingEstimate:
    violation_probability: float
    particles: int
    levels: int