function create_sentil_library(libName, overwrite)
%CREATE_SENTIL_LIBRARY Build the SENTIL Simulink block library with a masked monitor.
arguments
    libName (1, 1) string = "sentil_lib"
    overwrite (1, 1) logical = false
end

libFile = libName + ".slx";
if isfile(libFile) && ~overwrite
    load_system(libFile);
    return
end
if isfile(libFile) || bdIsLoaded(libName)
    close_system(libName, 0);
end

new_system(libName, 'Library');
set_param(libName, 'Lock', 'off');

block = libName + "/SENTIL Monitor";
add_block('simulink/User-Defined Functions/S-Function', block);
set_param(block, ...
    'FunctionName', 'sentil_s_function', ...
    'Parameters', 'formula_str, var_names_str, mode_idx, samples_int, noise_var_dbl, noise_file_str');

mask = Simulink.Mask.create(block);
mask.Type = 'SENTIL Monitor';
mask.Description = ['Runtime verification for Signal Temporal Logic and its ' ...
    'probabilistic extension. Monitors the input signal against the formula and ' ...
    'outputs the running robustness. Probabilistic mode widens the output to ' ...
    '[robustness, P, lower, upper], where P and its bounds hold the satisfaction ' ...
    'probability of a P[~p] formula and are NaN for a formula without one.'];

mask.addParameter('Type', 'edit', 'Name', 'formula_str', 'Prompt', 'Formula', ...
    'Evaluate', 'off');
mask.addParameter('Type', 'edit', 'Name', 'var_names_str', ...
    'Prompt', 'Input variables (comma-separated)', 'Evaluate', 'off');
mask.addParameter('Type', 'popup', 'TypeOptions', {'Deterministic', 'Probabilistic/SMC'}, ...
    'Name', 'mode_sel', 'Prompt', 'Mode', 'Evaluate', 'off');
mask.addParameter('Type', 'edit', 'Name', 'samples_int', 'Prompt', 'Monte Carlo samples', ...
    'Evaluate', 'on');
mask.addParameter('Type', 'edit', 'Name', 'noise_var_dbl', 'Prompt', 'Lifting noise variance', ...
    'Evaluate', 'on');
mask.addParameter('Type', 'edit', 'Name', 'noise_file_str', 'Prompt', 'Noise model file (optional)', ...
    'Evaluate', 'off');

mask.getParameter('formula_str').Value = 'always[0, 5](x > 0)';
mask.getParameter('var_names_str').Value = 'x';
mask.getParameter('mode_sel').Value = 'Deterministic';
mask.getParameter('samples_int').Value = '10000';
mask.getParameter('noise_var_dbl').Value = '0.1';
mask.getParameter('noise_file_str').Value = '';

% Mask fields 4 to 6 are the probabilistic-only ones.
visibilityCallback = [ ...
    'vis = get_param(gcb, ''MaskVisibilities''); ' ...
    'if strcmp(get_param(gcb, ''mode_sel''), ''Deterministic''); ' ...
    'vis{4} = ''off''; vis{5} = ''off''; vis{6} = ''off''; ' ...
    'else; ' ...
    'vis{4} = ''on''; vis{5} = ''on''; vis{6} = ''on''; ' ...
    'end; ' ...
    'set_param(gcb, ''MaskVisibilities'', vis);'];
mask.getParameter('mode_sel').Callback = visibilityCallback;

mask.Initialization = [ ...
    'mode_idx = find(strcmp({''Deterministic'', ''Probabilistic/SMC''}, mode_sel)) - 1;' newline ...
    'port_label(''input'', 1, ''signal'');' newline ...
    'if mode_idx == 0' newline ...
    '    port_label(''output'', 1, ''robustness'');' newline ...
    'else' newline ...
    '    port_label(''output'', 1, ''[robustness, P, lower, upper]'');' newline ...
    'end'];

save_system(libName, libFile);
close_system(libName);
end