function build_insulin_model(slx_model, target_bg, req_normo, req_hypo, sim_time, dt_fixed)
%BUILD_INSULIN_MODEL Assemble the UVA/Padova closed-loop artificial-pancreas model.

if bdIsLoaded(slx_model), close_system(slx_model, 0); end
new_system(slx_model);

add_block('simulink/Sources/From Workspace', ...
    [slx_model '/Meal_Input'], ...
    'VariableName', 'meal_ts', ...
    'Interpolate', 'on', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', [20 70 70 100]);

% Gut absorption, a first-order lag with time constant tau_c in minutes.
add_block('simulink/Continuous/Transfer Fcn', [slx_model '/Gut'], ...
    'Numerator', '[1]', ...
    'Denominator', '[tau_c*60 1]', ...
    'Position', [110 70 190 100]);

% Carb-to-BG conversion (mg/dL per gram of CHO, body-weight scaled)
add_block('simulink/Math Operations/Gain', [slx_model '/Carb_Gain'], ...
    'Gain', '3.5 * (70 / BW)', ...
    'Position', [220 70 270 100]);

% Endogenous glucose production (mg/dL per minute)
add_block('simulink/Sources/Constant', [slx_model '/EGP'], ...
    'Value', '0.4 * EGP', ...
    'Position', [220 20 270 50]);

add_block('simulink/Sources/Constant', [slx_model '/Target'], ...
    'Value', num2str(target_bg), ...
    'Position', [20 190 70 220]);

% u = saturate(Kp * (CGM - target), [0, 10]) in U/h.
add_block('simulink/Math Operations/Sum', [slx_model '/Err'], ...
    'Inputs', '+-', 'Position', [110 195 130 215]);
add_block('simulink/Math Operations/Gain', [slx_model '/Pump_Kp'], ...
    'Gain', 'Kp', 'Position', [160 190 200 220]);
add_block('simulink/Discontinuities/Saturation', ...
    [slx_model '/Pump_Sat'], ...
    'UpperLimit', '10', 'LowerLimit', '0', ...
    'Position', [220 190 260 220]);

% Insulin-mediated glucose disposal (mg/dL per minute)
add_block('simulink/Math Operations/Gain', [slx_model '/SI_Gain'], ...
    'Gain', 'SI/100', 'Position', [280 190 320 220]);

% Metabolic balance: dBG/dt [mg/dL/min] = +EGP + carb_effect - insulin.
add_block('simulink/Math Operations/Sum', [slx_model '/Metabolic'], ...
    'Inputs', '++-', ...
    'Position', [350 100 370 160]);

add_block('simulink/Math Operations/Gain', [slx_model '/Per_Second'], ...
    'Gain', '1/60', 'Position', [390 115 430 145]);

add_block('simulink/Continuous/Integrator', [slx_model '/BG'], ...
    'InitialCondition', num2str(target_bg), ...
    'Position', [450 115 480 145]);

% Band-Limited White Noise emits variance = Cov / Ts. Ts = 60 s matches CGM sampling.
add_block('simulink/Sources/Band-Limited White Noise', ...
    [slx_model '/CGM_Noise'], ...
    'Cov', '(CGM_sigma^2) * 60', ...
    'Ts', '60', ...
    'seed', '23341', ...
    'Position', [450 230 480 260]);
add_block('simulink/Math Operations/Sum', [slx_model '/CGM'], ...
    'Inputs', '++', 'Position', [520 125 540 175]);

% S-Function parameters in order: formula, variables, mode, samples, lifting variance, noise file.
p_normo = sprintf('''%s'', ''BG'', 0, 10000, 0.0, ''''', req_normo);
p_hypo = sprintf('''%s'', ''BG'', 0, 10000, 0.0, ''''', req_hypo);

add_block('simulink/User-Defined Functions/S-Function', ...
    [slx_model '/SENTIL_Normo'], ...
    'FunctionName', 'sentil_s_function', ...
    'Parameters', p_normo, ...
    'Position', [600 50 740 90]);
add_block('simulink/User-Defined Functions/S-Function', ...
    [slx_model '/SENTIL_Hypo'], ...
    'FunctionName', 'sentil_s_function', ...
    'Parameters', p_hypo, ...
    'Position', [600 170 740 210]);

add_block('simulink/Sinks/To Workspace', [slx_model '/Out_Normo'], ...
    'VariableName', 'rob_normo', 'SaveFormat', 'Array', ...
    'Position', [780 55 830 85]);
add_block('simulink/Sinks/To Workspace', [slx_model '/Out_Hypo'], ...
    'VariableName', 'rob_hypo', 'SaveFormat', 'Array', ...
    'Position', [780 175 830 205]);

add_line(slx_model, 'Meal_Input/1', 'Gut/1');
add_line(slx_model, 'Gut/1', 'Carb_Gain/1');
add_line(slx_model, 'Carb_Gain/1', 'Metabolic/2', 'autorouting', 'on');
add_line(slx_model, 'EGP/1', 'Metabolic/1', 'autorouting', 'on');
add_line(slx_model, 'Target/1', 'Err/2');
add_line(slx_model, 'Err/1', 'Pump_Kp/1');
add_line(slx_model, 'Pump_Kp/1', 'Pump_Sat/1');
add_line(slx_model, 'Pump_Sat/1', 'SI_Gain/1');
add_line(slx_model, 'SI_Gain/1', 'Metabolic/3', 'autorouting', 'on');
add_line(slx_model, 'Metabolic/1', 'Per_Second/1');
add_line(slx_model, 'Per_Second/1', 'BG/1');
add_line(slx_model, 'BG/1', 'CGM/1', 'autorouting', 'on');
add_line(slx_model, 'CGM_Noise/1', 'CGM/2');
add_line(slx_model, 'CGM/1', 'Err/1', 'autorouting', 'on');
add_line(slx_model, 'BG/1', 'SENTIL_Normo/1', 'autorouting', 'on');
add_line(slx_model, 'BG/1', 'SENTIL_Hypo/1', 'autorouting', 'on');
add_line(slx_model, 'SENTIL_Normo/1', 'Out_Normo/1');
add_line(slx_model, 'SENTIL_Hypo/1', 'Out_Hypo/1');

% Band-Limited White Noise is incompatible with variable-step tolerance control.
set_param(slx_model, ...
    'StopTime', num2str(sim_time), ...
    'Solver', 'ode3', ...
    'FixedStep', num2str(dt_fixed), ...
    'ReturnWorkspaceOutputs', 'on');
save_system(slx_model);
end