[[libsentil]]
arch = "x86_64"
libc = "glibc"
os = "linux"
git-tree-sha1 = "4821340839d1299b2f4bf35d696f7daf4d7a6130"
lazy = true

    [[libsentil.download]]
    sha256 = "41276f2bf08def8e2f42c933b79aefeaf0958cacaead8e2728bc3166ff72eac3"
    url = "https://github.com/sedislab/SENTIL/releases/download/v0.3.1/sentil-0.3.1-x86_64-linux-gnu-julia.tar.gz"

[[libsentil]]
arch = "aarch64"
libc = "glibc"
os = "linux"
git-tree-sha1 = "2adb409cb385fec4953eedfa4b98e6baa772ad8e"
lazy = true

    [[libsentil.download]]
    sha256 = "996b27647e52a864b1334d40c024e4cb8603148cc1ba7c43fe497ea4e49dc424"
    url = "https://github.com/sedislab/SENTIL/releases/download/v0.3.1/sentil-0.3.1-aarch64-linux-gnu-julia.tar.gz"

[[libsentil]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "af26d5844858d4cbf65925484d9f90b5b8f6f287"
lazy = true

    [[libsentil.download]]
    sha256 = "51f3539d324a284221c7f949ce125aab6d2751763d08912d4c37a4a7621203de"
    url = "https://github.com/sedislab/SENTIL/releases/download/v0.3.1/sentil-0.3.1-x86_64-apple-darwin-julia.tar.gz"

[[libsentil]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "4c3b1e59083a6e21271d9ba9efce3e8e34f41a39"
lazy = true

    [[libsentil.download]]
    sha256 = "7a12e1a1292ad291ae63f8b078cb60909e0bed9a3c12b3525ed0932ffe13ffb4"
    url = "https://github.com/sedislab/SENTIL/releases/download/v0.3.1/sentil-0.3.1-aarch64-apple-darwin-julia.tar.gz"

[[libsentil]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "2826e0da85e3a2b9dc9ce41e400ffc19446fc026"
lazy = true

    [[libsentil.download]]
    sha256 = "fb03aeff4ba8284d641876c63b6b7d661e7276c06fc85229db3bb711bcd46bb7"
    url = "https://github.com/sedislab/SENTIL/releases/download/v0.3.1/sentil-0.3.1-x86_64-pc-windows-msvc-julia.tar.gz"